### ISSUE TITLE
[Fail to build] Missing #include following fixes #90

### ISSUE THREAD

**Issue by SlySven** [edbee/edbee-lib#111]
In this line (introduced in bb579e6c73b1fdd7a048c283b25de2cdef3d3967) :
https://github.com/edbee/edbee-lib/blob/fce89540c784eceb58d9c4845dfe361b4ee8c15d/edbee-lib/edbee/views/textrenderer.cpp#L200
you have used a function `(int) round(double)` from the maths library but you have not got an `#include <maths.h>` at the top of the file - **this is causing build failures in some situations**:
```sh
../3rdparty/edbee-lib/edbee-lib/edbee/views/textrenderer.cpp: In member function ‘int edbee::TextRenderer::xPosForColumn(int, int)’:
../3rdparty/edbee-lib/edbee-lib/edbee/views/textrenderer.cpp:201:12: error: ‘round’ was not declared in this scope
     return round(x);
            ^~~~~
```

**Comment by gamecreature** [comment]
@SlySven I don't get your comment. Latest master on line 200 contains a qRound..

**Comment by SlySven** [comment]
Sorry, I was looking at an older version (as I did cross-reference in the post) but that was seven commits ago and you reported and fixed it (#106) 55e675a9698d7c0478296150d948c892da724e6e - so sorry for disturbing you,,, 😊
