### ISSUE TITLE
Errors when attempting to build with Qt 6.3.0

### ISSUE THREAD

**Issue by BlackStar-EoP** [edbee/edbee-lib#133]
Yo GameCreature, here's my output from compiling with VS2022 and Qt 6.3.0, compiler set to ISO C++20 (Can try with 17, but will probably result in the same)

edbee-lib\edbee-lib\edbee\util\mem\debug_allocs.cpp(36,34): error C2039: 'Recursive': is not a member of 'QMutex'
edbee-lib\edbee-lib\edbee\util\mem\debug_allocs.cpp(36,44): error C2065: 'Recursive': undeclared identifier
edbee\devisetexteditor.cpp(80,13): error C2039: 'setMargin': is not a member of 'QBoxLayout'
edbee\findwidget.cpp(112,13): error C2039: 'setMargin': is not a member of 'QHBoxLayout'
edbee-lib\edbee-lib\edbee\models\textdocumentfilter.h(11,7): error C2371: 'QStringList': redefinition; different basic types
edbee-lib\edbee-lib\edbee\models\textdocument.cpp(207,49): error C2027: use of undefined type 'QStringList'
edbee-lib\edbee-lib\edbee\models\textdocument.cpp(207,74): error C2664: 'void edbee::TextDocument::replaceRangeSet(edbee::TextRangeSet &,const QString &,bool)': cannot convert argument 2 from 'bool' to 'const QString &'
edbee-lib\edbee-lib\edbee\models\textdocument.cpp(213,1): error C2511: 'void edbee::TextDocument::replaceRangeSet(edbee::TextRangeSet &,const QStringList &,bool)': overloaded member function not found in 'edbee::TextDocument'
edbee-lib\edbee-lib\edbee\models\textdocument.cpp(215,17): error C2079: 'texts' uses undefined class 'QStringList'
edbee-lib\edbee-lib\edbee\models\textdocument.cpp(215,23): error C2027: use of undefined type 'QStringList'
edbee-lib\edbee-lib\edbee\models\textdocument.cpp(216,9): error C2352: 'edbee::TextDocument::documentFilter': illegal call of non-static member function
edbee-lib\edbee-lib\edbee\models\textdocument.cpp(217,9): error C2352: 'edbee::TextDocument::documentFilter': illegal call of non-static member function
edbee-lib\edbee-lib\edbee\models\textdocument.cpp(217,50): error C2671: 'edbee::TextDocument::replaceRangeSet': static member functions do not have 'this' pointers
edbee-lib\edbee-lib\edbee\models\textdocument.cpp(235,35): error C2352: 'edbee::TextDocument::executeAndGiveChange': illegal call of non-static member function
edbee-lib\edbee-lib\edbee\models\textdocumentfilter.h(11,7): error C2371: 'QStringList': redefinition; different basic types
edbee-lib\edbee-lib\edbee\views\components\texteditorcomponent.cpp(392,69): error C2039: 'MidButton': is not a member of 'Qt'
edbee-lib\edbee-lib\edbee\views\components\texteditorcomponent.cpp(392,79): error C2065: 'MidButton': undeclared identifier
edbee-lib\edbee-lib\edbee\views\components\texteditorcomponent.cpp(410,86): error C2039: 'MidButton': is not a member of 'Qt'
edbee-lib\edbee-lib\edbee\views\components\texteditorcomponent.cpp(410,96): error C2065: 'MidButton': undeclared identifier
edbee-lib\edbee-lib\edbee\models\texteditorkeymap.cpp(75,5): error C2440: 'initializing': cannot convert from 'QMultiHash<QString,edbee::TextEditorKey *>::const_iterator' to 'QHash<Key,T>::const_iterator'
edbee-lib\edbee-lib\edbee\models\texteditorkeymap.cpp(75,109): error C2679: binary '!=': no operator found which takes a right-hand operand of type 'QHash<Key,T>::const_iterator' (or there is no acceptable conversion)
edbee-lib\edbee-lib\edbee\models\texteditorkeymap.cpp(87,75): error C2440: 'initializing': cannot convert from 'QMultiHash<QString,edbee::TextEditorKey *>::const_iterator' to 'QHash<Key,T>::const_iterator'
edbee-lib\edbee-lib\edbee\models\texteditorkeymap.cpp(88,30): error C2679: binary '!=': no operator found which takes a right-hand operand of type 'QHash<Key,T>::const_iterator' (or there is no acceptable conversion)
edbee-lib\edbee-lib\edbee\models\texteditorkeymap.cpp(204,66): error C2440: 'initializing': cannot convert from 'QMultiHash<QString,edbee::TextEditorKey *>::iterator' to 'QHash<Key,T>::iterator'
edbee-lib\edbee-lib\edbee\models\texteditorkeymap.cpp(205,32): error C2679: binary '!=': no operator found which takes a right-hand operand of type 'QHash<Key,T>::iterator' (or there is no acceptable conversion)
edbee-lib\edbee-lib\edbee\models\texteditorkeymap.cpp(321,5): error C2440: 'initializing': cannot convert from 'QMultiHash<QString,edbee::TextEditorKey *>::const_iterator' to 'QHash<Key,T>::const_iterator'
edbee-lib\edbee-lib\edbee\models\texteditorkeymap.cpp(321,109): error C2679: binary '!=': no operator found which takes a right-hand operand of type 'QHash<Key,T>::const_iterator' (or there is no acceptable conversion)
edbee-lib\edbee-lib\edbee\texteditorwidget.cpp(82,13): error C2039: 'setMargin': is not a member of 'QVBoxLayout'

**Comment by BlackStar-EoP** [comment]
QT += core5compat needs to be done for a couple of things

Here's the diff I made to get devise2 to build:

diff --git a/edbee-lib/edbee/models/textdocumentfilter.h b/edbee-lib/edbee/models/textdocumentfilter.h
index e40dbd7..291e3e8 100644
--- a/edbee-lib/edbee/models/textdocumentfilter.h
+++ b/edbee-lib/edbee/models/textdocumentfilter.h
@@ -8,7 +8,6 @@
 #include "edbee/exports.h"
 
 class QString;
-class QStringList;
 
 namespace edbee {
 
diff --git a/edbee-lib/edbee/models/texteditorkeymap.cpp b/edbee-lib/edbee/models/texteditorkeymap.cpp
index 17f3005..5e17c03 100644
--- a/edbee-lib/edbee/models/texteditorkeymap.cpp
+++ b/edbee-lib/edbee/models/texteditorkeymap.cpp
@@ -72,7 +72,7 @@ TextEditorKeyMap::~TextEditorKeyMap()
 /// @param keyMap the keymap to copy the keys from
 void TextEditorKeyMap::copyKeysTo(TextEditorKeyMap* keyMap)
 {
-    for( QHash<QString,TextEditorKey*>::const_iterator itr = keyMap_.constBegin(); itr != keyMap_.constEnd(); ++itr ) {
+    for( auto itr = keyMap_.constBegin(); itr != keyMap_.constEnd(); ++itr ) {
         keyMap->keyMap_.insert( itr.key(), itr.value()->clone() );
     }
 }
@@ -84,7 +84,7 @@ void TextEditorKeyMap::copyKeysTo(TextEditorKeyMap* keyMap)
 /// @return the keysequence or 0 if not found
 TextEditorKey* TextEditorKeyMap::get(const QString& name) const
 {
-    QHash<QString,TextEditorKey*>::const_iterator itr = keyMap_.find(name);
+    auto itr = keyMap_.find(name);
     if( itr != keyMap_.end() ) { return itr.value(); }
     if( parentRef_ ) { return parentRef_->get(name); }
     return nullptr;
@@ -201,7 +201,7 @@ void TextEditorKeyMap::replace(const QString& name, TextEditorKey* sequence)
 QString TextEditorKeyMap::findBySequence(QKeySequence sequence, QKeySequence::SequenceMatch& match)
 {
     // find the current map
-    QHash<QString,TextEditorKey*>::iterator itr = keyMap_.begin();
+    auto itr = keyMap_.begin();
     while (itr != keyMap_.end()) {
         match =  sequence.matches( itr.value()->sequence() );
         if( match != QKeySequence::NoMatch ) {
@@ -318,7 +318,7 @@ QKeySequence::StandardKey TextEditorKeyMap::standardKeyFromString( const QString
 QString TextEditorKeyMap::toString() const
 {
     QString str;
-    for( QHash<QString,TextEditorKey*>::const_iterator itr = keyMap_.constBegin(); itr != keyMap_.constEnd(); ++itr ) {
+    for( auto itr = keyMap_.constBegin(); itr != keyMap_.constEnd(); ++itr ) {
         if( !str.isEmpty()) str.append(",");
         str.append( QStringLiteral("%1:%2").arg(itr.key()).arg(itr.value()->sequence().toString()) );
     }
diff --git a/edbee-lib/edbee/texteditorwidget.cpp b/edbee-lib/edbee/texteditorwidget.cpp
index 101e012..354acfd 100644
--- a/edbee-lib/edbee/texteditorwidget.cpp
+++ b/edbee-lib/edbee/texteditorwidget.cpp
@@ -79,7 +79,7 @@ TextEditorWidget::TextEditorWidget(QWidget* parent)
 
     QVBoxLayout* layout = new QVBoxLayout(this);
     layout->addWidget( scrollAreaRef_ );
-    layout->setMargin(0);
+    layout->setContentsMargins(0, 0, 0, 0);
 
     setLayout(layout);
     setFocusProxy( editCompRef_ );
diff --git a/edbee-lib/edbee/util/mem/debug_allocs.cpp b/edbee-lib/edbee/util/mem/debug_allocs.cpp
index 89b1c7e..f03a59c 100644
--- a/edbee-lib/edbee/util/mem/debug_allocs.cpp
+++ b/edbee-lib/edbee/util/mem/debug_allocs.cpp
@@ -33,7 +33,7 @@ DebugAllocationList::DebugAllocationList()
     , running_(false)
     , started_(false)
 {
-    mutex_ = new QMutex( QMutex::Recursive );
+    mutex_ = new QMutex();
     start(false);
     checkDelete_ = false;
 }
diff --git a/edbee-lib/edbee/views/components/texteditorautocompletecomponent.cpp b/edbee-lib/edbee/views/components/texteditorautocompletecomponent.cpp
index 892dd12..89fa035 100644
--- a/edbee-lib/edbee/views/components/texteditorautocompletecomponent.cpp
+++ b/edbee-lib/edbee/views/components/texteditorautocompletecomponent.cpp
@@ -10,7 +10,6 @@
 #include <QTextEdit>
 #include <QtGui>
 #include <QTime>
-#include <QDesktopWidget>
 
 #include "edbee/edbee.h"
 #include "edbee/models/textautocompleteprovider.h"
@@ -39,7 +38,7 @@ TextEditorAutoCompleteComponent::TextEditorAutoCompleteComponent(TextEditorContr
     /// initialize the widget
     QBoxLayout* layout = new QBoxLayout(QBoxLayout::TopToBottom);
     layout->setSpacing(0);
-    layout->setMargin(0);
+    layout->setContentsMargins(0, 0, 0, 0);
 
     menuRef_ = new QMenu(this);
     listWidgetRef_ = new QListWidget(menuRef_);
@@ -192,7 +191,7 @@ void TextEditorAutoCompleteComponent::showInfoTip()
 
     QPoint newLoc(listWidgetRef_->parentWidget()->mapToGlobal(r.topRight()).x() + xOffset, listWidgetRef_->parentWidget()->mapToGlobal(r.topRight()).y() + 1);
 
-    QRect screen = QApplication::desktop()->availableGeometry(this);
+    QRect screen = QApplication::primaryScreen()->availableGeometry();
     if( newLoc.x() + infoTipRef_->width() > screen.x() + screen.width() && (menuRef_->x() - infoTipRef_->width() - 1) >= 0 ){
         newLoc.setX(menuRef_->x() - infoTipRef_->width() - 1);
     }
@@ -539,7 +538,7 @@ void FakeToolTip::paintEvent(QPaintEvent*)
     TextRenderer* renderer = controller()->textRenderer();
     TextTheme* themeRef_ = renderer->theme();
 
-    opt->init(this);
+    opt->initFrom(this);
     style->drawPrimitive(QStyle::PE_PanelTipLabel, opt, p);
 
     tipText->setDefaultFont(controller()->textDocument()->config()->font());
@@ -570,7 +569,7 @@ void FakeToolTip::resizeEvent(QResizeEvent *)
 {
     QStyleHintReturnMask frameMask;
     QStyleOption option;
-    option.init(this);
+    option.initFrom(this);
 }
 
 }// edbee
diff --git a/edbee-lib/edbee/views/components/texteditorcomponent.cpp b/edbee-lib/edbee/views/components/texteditorcomponent.cpp
index dd68fef..ab5dcdf 100644
--- a/edbee-lib/edbee/views/components/texteditorcomponent.cpp
+++ b/edbee-lib/edbee/views/components/texteditorcomponent.cpp
@@ -389,7 +389,7 @@ QVariant TextEditorComponent::inputMethodQuery( Qt::InputMethodQuery p ) const
 /// @param event the mouse event
 void TextEditorComponent::mousePressEvent(QMouseEvent* event)
 {
-    if( event->button() == Qt::LeftButton || event->button() == Qt::MidButton ) {
+    if( event->button() == Qt::LeftButton || event->button() == Qt::MiddleButton ) {
         TextRenderer* renderer = textRenderer();
 
 //        int x = renderer->widgetXToXpos( event->x() + horizontalScrollBar()->value() );
@@ -407,7 +407,7 @@ void TextEditorComponent::mousePressEvent(QMouseEvent* event)
                 controller()->moveCaretTo( line, col, event->modifiers()&Qt::ShiftModifier );
             }
         }
-        if( QApplication::clipboard()->supportsSelection() && event->button() == Qt::MidButton ) { // X11 / linux support middle button paste
+        if( QApplication::clipboard()->supportsSelection() && event->button() == Qt::MiddleButton ) { // X11 / linux support middle button paste
             controller()->moveCaretTo( line, col, false ); // clear actual selection and put cursor under mouse
             controller()->replaceSelection( QApplication::clipboard()->text(QClipboard::Selection), CoalesceId_Paste );
             controller()->updateStatusText();
diff --git a/vendor/qslog/QsLogDestFile.cpp b/vendor/qslog/QsLogDestFile.cpp
index 00ae8c9..565876b 100644
--- a/vendor/qslog/QsLogDestFile.cpp
+++ b/vendor/qslog/QsLogDestFile.cpp
@@ -149,7 +149,7 @@ QsLogging::FileDestination::FileDestination(const QString& filePath, RotationStr
         std::cerr << "QsLog: could not open log file " << qPrintable(filePath);
     }
     mOutputStream.setDevice(&mFile);
-    mOutputStream.setCodec(QTextCodec::codecForName("UTF-8"));
+    mOutputStream.setEncoding(QStringConverter::Utf8);
 
     mRotationStrategy->setInitialInfo(mFile);
 }
@@ -167,7 +167,7 @@ void QsLogging::FileDestination::write(const LogMessage& message)
         }
         mRotationStrategy->setInitialInfo(mFile);
         mOutputStream.setDevice(&mFile);
-        mOutputStream.setCodec(QTextCodec::codecForName("UTF-8"));
+        mOutputStream.setEncoding(QStringConverter::Utf8);
     }
 
     mOutputStream << utf8Message << '\n';
