### ISSUE TITLE
Compiling edbee with Qt6 on macOS fails

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#141]
While compiling edbee. with Qt6 on Linux works fine, macOS fails with this:

```
[  7%] Building CXX object 3rdparty/edbee-lib/edbee-lib/qslog/CMakeFiles/QsLog.dir/QsLogDest.cpp.o
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:59:58: error: 'path' is unavailable: introduced in macOS 10.15
inline QString fromFilesystemPath(const std::filesystem::path &path)
                                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:442:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:64:40: error: 'native' is unavailable: introduced in macOS 10.15
    return QString::fromStdString(path.native());
                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:775:22: note: 'native' has been explicitly marked unavailable here
  const string_type& native() const noexcept { return __pn_; }
                     ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:68:25: error: 'path' is unavailable: introduced in macOS 10.15
inline std::filesystem::path toFilesystemPath(const QString &path)
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:442:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:70:29: error: 'path' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),
                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:442:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:70:12: error: 'path<const char16_t *>' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:488:3: note: 'path<const char16_t *>' has been explicitly marked unavailable here
  path(_InputIt __first, _InputIt __last, format = format::auto_format) {
  ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:70:12: error: 'path' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:488:3: note: 'path' has been explicitly marked unavailable here
  path(_InputIt __first, _InputIt __last, format = format::auto_format) {
  ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:70:12: error: '~path' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:505:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:128:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemFileName() const
                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:442:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:190:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemSymLinkTarget() const
                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:442:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:195:29: error: 'path' is unavailable: introduced in macOS 10.15
    static std::filesystem::path filesystemSymLinkTarget(const T &fileName)
                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:442:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:129:14: error: '~path' is unavailable: introduced in macOS 10.15
    { return QtPrivate::toFilesystemPath(fileName()); }
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:505:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDest.cpp:28:
In file included from /Users/vadim.peretokin/Programs/Mudlet/3rdparty/edbee-lib/vendor/qslog/QsLogDestFile.h:30:
In file included from /opt/homebrew/opt/qt/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/opt/qt/lib/QtCore.framework/Headers/qfile.h:192:16: error: '~path' is unavailable: introduced in macOS 10.15
        return QtPrivate::toFilesystemPath(symLinkTarget());
               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__filesystem/path.h:505:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
12 errors generated.
make[2]: *** [3rdparty/edbee-lib/edbee-lib/qslog/CMakeFiles/QsLog.dir/QsLogDest.cpp.o] Error 1
make[1]: *** [3rdparty/edbee-lib/edbee-lib/qslog/CMakeFiles/QsLog.dir/all] Error 2
make: *** [all] Error 2
```

How to fix this error?

**Comment by gamecreature** [comment]
That's a good question. It looks like Qt 6.5 uses `std::filesystem::path` which is only is supported on `macOS 10.15+`.

<https://stackoverflow.com/questions/77398795/c-std-error-path-is-unavailable-introduced-in-macos-10-15>

A solution from other sites is to build with -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15

(I will check later today if it builds on my system)

**Comment by gamecreature** [comment]
The edbee-app just compiled it on my Mac: QT 6.6.1 (Clang 13.0 (Apple), arm64) / QT Creator 12.0.1
